"""race times

Revision ID: 5c4c148f0030
Revises: f6235b565cd7
Create Date: 2026-08-27 15:07:36.500030
"""
from alembic import op
import sqlalchemy as sa


revision = '5c4c148f0030'
down_revision = 'f6235b565cd7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('race_5k_time_s', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('race_10k_time_s', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('race_hm_time_s', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('race_marathon_time_s', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'race_marathon_time_s')
    op.drop_column('users', 'race_hm_time_s')
    op.drop_column('users', 'race_10k_time_s')
    op.drop_column('users', 'race_5k_time_s')
    # ### end Alembic commands ###
