"""initial schema

Revision ID: 8e7e506a19cd
Revises: 
Create Date: 2026-08-27 08:16:34.781129
"""
from alembic import op
import sqlalchemy as sa


revision = '8e7e506a19cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ATHLETE', 'TRAINER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('hr_rest', sa.Float(), nullable=True),
    sa.Column('hr_max', sa.Float(), nullable=True),
    sa.Column('threshold_pace_sec_per_km', sa.Float(), nullable=True),
    sa.Column('vo2max_pace_sec_per_km', sa.Float(), nullable=True),
    sa.Column('zones_last_updated', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('GARMIN', 'POLAR', 'COROS', 'STRAVA', 'MANUAL', name='datasource'), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('avg_hr', sa.Float(), nullable=True),
    sa.Column('splits', sa.JSON(), nullable=False),
    sa.Column('daily_load', sa.Float(), nullable=False),
    sa.Column('zone_km', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_activities_athlete_id'), 'activities', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_activities_day'), 'activities', ['day'], unique=False)
    op.create_table('oauth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('GARMIN', 'POLAR', 'COROS', 'STRAVA', 'MANUAL', name='datasource'), nullable=False),
    sa.Column('access_token', sa.String(length=1000), nullable=False),
    sa.Column('refresh_token', sa.String(length=1000), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('provider_user_id', sa.String(length=255), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_tokens_athlete_id'), 'oauth_tokens', ['athlete_id'], unique=False)
    op.create_table('planned_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_zone', sa.String(length=20), nullable=True),
    sa.Column('target_distance_km', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planned_sessions_athlete_id'), 'planned_sessions', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_planned_sessions_day'), 'planned_sessions', ['day'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_planned_sessions_day'), table_name='planned_sessions')
    op.drop_index(op.f('ix_planned_sessions_athlete_id'), table_name='planned_sessions')
    op.drop_table('planned_sessions')
    op.drop_index(op.f('ix_oauth_tokens_athlete_id'), table_name='oauth_tokens')
    op.drop_table('oauth_tokens')
    op.drop_index(op.f('ix_activities_day'), table_name='activities')
    op.drop_index(op.f('ix_activities_athlete_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_table('users')
    # ### end Alembic commands ###
