"""oauth tokens unique per athlete provider

Revision ID: f6235b565cd7
Revises: 8e7e506a19cd
Create Date: 2026-08-27 08:32:12.255132
"""
from alembic import op
import sqlalchemy as sa


revision = 'f6235b565cd7'
down_revision = '8e7e506a19cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_oauth_tokens_athlete_provider', 'oauth_tokens', ['athlete_id', 'provider'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_oauth_tokens_athlete_provider', 'oauth_tokens', type_='unique')
    # ### end Alembic commands ###
